# μ»¤λ°‹ λ¶„μ„μ΄ ν¬ν•¨λ κ²€μ¦
# μ‹¤ν¨ν• μ»¤λ°‹λ“¤μ„ μμ„Έν λ¶„μ„ν•©λ‹λ‹¤

name: μƒμ„Έ μ»¤λ°‹ λ¶„μ„

on:
  pull_request:
    types: [ready_for_review, synchronize]

jobs:
  analyze-commits:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    
    steps:
      - uses: actions/checkout@v4
      
      - name: μ»¤λ°‹ λ©”μ‹μ§€ κ²€μ¦
        uses: yourssu/actions/validation/commit-validator@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          team_config: "yourssu-backend"
        id: validation
        
      - name: κ²€μ¦ κ²°κ³Ό μ¶λ ¥
        run: |
          echo "κ²€μ¦ κ²°κ³Ό: ${{ steps.validation.outputs.is_valid }}"
          echo "μ΄ μ»¤λ°‹ μ: ${{ steps.validation.outputs.total_commits }}"
          
      - name: μ‹¤ν¨ν• μ»¤λ°‹ λ¶„μ„
        if: steps.validation.outputs.is_valid == 'false'
        uses: actions/github-script@v7
        with:
          script: |
            const invalidCommits = JSON.parse('${{ steps.validation.outputs.invalid_commits }}');
            
            console.log(`π” ${invalidCommits.length}κ°μ μ ν¨ν•μ§€ μ•μ€ μ»¤λ°‹μ„ λ°κ²¬ν–μµλ‹λ‹¤:`);
            console.log('');
            
            for (const commit of invalidCommits) {
              console.log(`β μ»¤λ°‹: ${commit.sha}`);
              console.log(`   λ©”μ‹μ§€: "${commit.message}"`);
              console.log(`   μ‘μ„±μ: ${commit.author}`);
              console.log(`   λ‚ μ§: ${commit.date}`);
              console.log('');
            }
            
            // μ΄ λ¶„μ„ κ²°κ³Ό
            const totalCommits = parseInt('${{ steps.validation.outputs.total_commits }}');
            const validCommits = totalCommits - invalidCommits.length;
            console.log(`π“ μ΄ ${totalCommits}κ° μ»¤λ°‹ μ¤‘ ${validCommits}κ° ν†µκ³Ό, ${invalidCommits.length}κ° μ‹¤ν¨`);
        
      - name: μ„±κ³µν• κ²½μ°
        if: steps.validation.outputs.is_valid == 'true'
        run: |
          echo "β… λ¨λ“  μ»¤λ°‹μ΄ λ„¤μ΄λ° μ»¨λ²¤μ…μ„ λ”°λ¦…λ‹λ‹¤!"
          echo "μ΄ ${{ steps.validation.outputs.total_commits }}κ° μ»¤λ°‹ κ²€μ¦ μ™„λ£"